feat(icons): add bell and share icons
razorpay/blade pull request #184
Opened 2020-08-27 09:09 UTC by shridhar52war

<img width="82" alt="Screenshot 2020-08-27 at 2 36 16 PM" src="https://user-images.githubusercontent.com/56016210/91421005-05897900-e873-11ea-8979-63273de0451a.png">
<img width="43" alt="Screenshot 2020-08-27 at 2 36 26 PM" src="https://user-images.githubusercontent.com/56016210/91421014-07533c80-e873-11ea-9921-de9fa87db93a.png">

2020-08-27 09:12 UTC, shubhnik approved these changes

2020-08-28 05:06 UTC, shubhnik requested changes

2020-08-28 05:06 UTC, shubhnik commented on src/icons/index.js
> +  message: require('./Message').default,
abcd "e" fgh "i"

2020-08-28 05:07 UTC, chaitanyadeorukhkar commented on src/icons/index.js
> +  message: require('./Message').default,
++++

2020-08-28 05:13 UTC, shridhar52war commented on src/icons/index.js
> +  message: require('./Message').default,
🤦

2020-08-28 05:34 UTC, chaitanyadeorukhkar approved these changes

2020-08-28 05:34 UTC, shubhnik approved these changes

2020-08-28 05:42 UTC, merged