build(reanimated): update reanimated and add it in peerDependencies
razorpay/blade pull request #189
Opened 2020-09-08 07:39 UTC by shubhnik

2020-09-08 10:49 UTC, chaitanyadeorukhkar requested changes

2020-09-08 10:49 UTC, chaitanyadeorukhkar commented on package.json
> +    "react-native-reanimated": "1.9.0",
```suggestion
    "react-native-reanimated": "^1.9.0",
```

2020-09-08 10:49 UTC, shubhnik commented
Need this because reanimated is also a dependency in platoon.

2020-09-08 11:29 UTC, chaitanyadeorukhkar approved these changes

2020-09-09 07:32 UTC, shridhar52war approved these changes

2020-09-09 08:05 UTC, merged