docs: add rfc template
razorpay/blade pull request #229
Opened 2021-01-12 07:59 UTC by kamleshchandnani

2021-02-10 11:26 UTC, saurav12 requested changes
Everything I've pointed has been replicated on Figma as well. Please update here as well.

2021-02-10 11:26 UTC, saurav12 commented on packages/blade/tokens/global/colors.ts
>      warmGray: colorNeutralScale;
Convert `warmGray` to `ashGrayLight`.

2021-02-10 11:26 UTC, saurav12 commented on packages/blade/tokens/global/colors.ts
>      coolGray: colorNeutralScale;
Convert `coolGray` to `ashGrayDark`.

2021-02-10 11:26 UTC, saurav12 commented on packages/blade/tokens/global/colors.ts
> +    warmGray: {
Convert `warmGray` to `ashGrayLight`.

2021-02-10 11:26 UTC, saurav12 commented on packages/blade/tokens/global/colors.ts
>      coolGray: {
Convert `coolGray` to `ashGrayDark`.

2021-02-10 11:26 UTC, saurav12 commented on packages/blade/tokens/theme/neoTheme.ts
> +          onDark: globalColors.chromatic.emerald[500],
Change values of `secondary.500` to `cider[600]` for **neoTheme**,
```
onLight: globalColors.chromatic.cider[600],
onDark: globalColors.chromatic.cider[600],
```

2021-02-15 10:31 UTC, dhruvdutt commented on .eslintrc.js
> +    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: false }],
Strangely this is not already existing in kent's or prettier's recommended config. We should add it to universe config as well.

2021-02-15 10:31 UTC, dhruvdutt approved these changes

2021-02-18 11:45 UTC, chaitanyadeorukhkar approved these changes

2021-02-19 07:32 UTC, merged