build(blade): update version
razorpay/blade pull request #733
Opened 2022-10-06 08:33 UTC by rzpcibot

This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
## @razorpay/blade@3.0.0

### Major Changes

-   3aebc58: feat(Typography): make `size` prop consistent for `Heading`, `Title`, and `Text`

    > **Warning**
    >
    > Breaking Change!
    > This is a breaking change for apps that are using `Title` or `Heading` component from blade. Rest of the apps can upgrade without any migrations.

    #### Migration

    _**Tip:** If you're using TypeScript, run `yarn tsc` and that should throw errors wherever a change is required._

    1.  **`<Title />`:** Rename `variant` prop to `size` in Title

    ```diff
    - <Title variant="small">Some Title</Title>
    + <Title size="small">Some Title</Title>
    ```

    2.  **`<Heading />`:** Rename `variant` prop to `size` if the value is `small`, `medium,` or `large`. No change is required on `variant="subheading"`.

    ```diff
    <Heading variant="subheading">Nothing changes here</Heading> // No change here

    - <Heading variant="medium">Medium Heading</Heading>
    + <Heading size="medium">Medium Heading</Heading>
    ```

    ##### Edge Cases

    Make sure to follow migration on new component if `Title` or `Heading` from blade is overriden with styled-components.

    ```diff
    const MyTitle = styled(Title)`
      // some styles
    `

    - <MyTitle variant="large" />
    + <MyTitle size="large" />
    ```

-   e16c154: feat(PasswordInput)!: rename from `PasswordField` to `PasswordInput`

### Minor Changes

-   eeba339: feat(Code): add `<Code />` component :shipit:

2022-10-06 08:57 UTC, saurabhdaware requested changes
Will release this and #730 in the same version

2022-10-07 06:06 UTC, saurabhdaware commented
Waiting for `PasswordField` name change. Can be merged after that // cc @divyanshu013

2022-10-07 10:03 UTC, divyanshu013 approved these changes

2022-10-07 10:26 UTC, saurabhdaware approved these changes

2022-10-07 10:27 UTC, merged